const CartActionTypes = {
  INCREASE_ITEM_AMOUNT: "INCREASE_ITEM_AMOUNT",
  REMOVE_ITEM: "REMOVE_ITEM",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  TOGGLE_ITEM_CHECKBOX: "TOGGLE_ITEM_CHECKBOX",
  TOGGLE_ALL_SELECT_CHECKBOX: "TOGGLE_ALL_SELECT_CHECKBOX",
  CHECK_ALL_SELECT_CHECKBOX: "CHECK_ALL_SELECT_CHECKBOX",
  DELETE_SELECTED_ITEMS: "DELETE_SELECTED_ITEMS",
  SELECTED_ITEMS_TOTAL_PRICE: "SELECTED_ITEMS_TOTAL_PRICE",
  GET_SELECTED_ITEMS_AMOUNT: "GET_SELECTED_ITEMS_AMOUNT",
  GET_CART_ITEMS: "GET_CART_ITEMS",
  ADD_ITEM_TO_CART_FROM_PRODUCT_PAGE: "ADD_ITEM_TO_CART_FROM_PRODUCT_PAGE",
  DELETE_SOLDOUT_ITEMS: "DELETE_SOLDOUT_ITEMS",
};

export default CartActionTypes;
