const CartActionTypes = {
  INCREASE_ITEM_AMOUNT: "INCREASE_ITEM_AMOUNT",
  DECREASE_ITEM_AMOUNT: "DECREASE_ITEM_AMOUNT",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  TOGGLE_ITEM_CHECKBOX: "TOGGLE_ITEM_CHECKBOX",
  TOGGLE_ALL_SELECT_CHECKBOX: "TOGGLE_ALL_SELECT_CHECKBOX",
  CHECK_ALL_SELECT_CHECKBOX: "CHECK_ALL_SELECT_CHECKBOX",
  DELETE_SELECTED_ITEMS: "DELETE_SELECTED_ITEMS",
  SELECTED_ITEMS_TOTAL_PRICE: "SELECTED_ITEMS_TOTAL_PRICE",
  GET_SELECTED_ITEMS_AMOUNT: "GET_SELECTED_ITEMS_AMOUNT",
  GET_CART_ITEMS: "GET_CART_ITEMS",
  ADD_ITEM_TO_CART: "ADD_ITEM_TO_CART",
  DELETE_SOLDOUT_ITEMS: "DELETE_SOLDOUT_ITEMS",
  USER_LOGOUT_CLEAR_CART: "USER_LOGOUT_CLEAR_CART",
  CHECKOUT_CHECKED_ITEMS: "CHECKOUT_CHECKED_ITEMS",
};

export default CartActionTypes;
