const PurchaseActionTypes = {
  GET_PURCHASE_LIST: "GET_PURCHASE_LIST",
  LOGOUT_CLEAR_PURCHASE_LIST: "LOGOUT_CLEAR_PURCHASE_LIST",
  ORDER_PURCHASE_LIST: "ORDER_PURCHASE_LIST",
};

export default PurchaseActionTypes;
