const UserActionTypes = {
  GET_CURRENT_USER: "GET_CURRENT_USER",
  USER_LOGOUT: "USER_LOGOUT",
  GET_TOKEN: "GET_TOKEN",
  CLEAR_TOKEN: "CLEAR_TOKEN",
  ADD_MILEAGE: "ADD_MILEAGE",
};

export default UserActionTypes;
