const FrequentlyPurchaseActionTypes = {
  FREQUENTLY_PURCHASE_ITEMS_ORDER_ALL: "FREQUENTLY_PURCHASE_ITEMS_ORDER_ALL",
  CLEAR_FREQUENTLY_PURCHASE_ITEM_LIST: "CLEAR_FREQUENTLY_PURCHASE_ITEM_LIST",
};

export default FrequentlyPurchaseActionTypes;
