const FrequentlyPurchaseActionTypes = {
  FREQUENTLY_PURCHASE_ITEMS_ORDER_ALL: "FREQUENTLY_PURCHASE_ITEMS_ORDER_ALL",
  CLEAR_FREQUENTLY_PURCHASE_ITEM_LIST: "CLEAR_FREQUENTLY_PURCHASE_ITEM_LIST",
  GET_FREQUENTLY_PURCHASE_ITEMS: "GET_FREQUENTLY_PURCHASE_ITEMS",
  ADD_TO_CARTLIST: "ADD_TO_CARTLIST",
};

export default FrequentlyPurchaseActionTypes;
